apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    tier: db
    type: prod
spec:
  containers:
    - name: mysql-container
      image: mysql
  volumes:
    - name: app-secret-volume
      secret:
        secretName: app-secret


##This injects the secrets in the pod by creating and attaching a volume to the pod which contains the secrets as a file.

## ls /opt/app-secret-volume
## DB_Host  DB_User  DB_Password

## cat /opt/app-secret-volume/DB_Password
## paswrd