apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    tier: backend
    type: db
spec:
  containers:
    - name: mysql-container
      image: mysql
      envFrom:
        - secretRef:
            name: app-secret

###kubectl create -f secret-injection-in-pod.yaml -- creates the pod with secrets injected 