apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    tier: backend
    type: prod
spec:
  containers:
    - name: mysql-container
      image: mysql
      env:
        - name: DB_Password
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_Password

##Here only DB_PASSWORD secret is injected from the app-secret named secret
