apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    tier: frontend
    type: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx
    envFrom:
    - configMapRef:
        name: app_config
      