apiVersion: v1
kind: Pod
metadata:
  name: webapp-green
  labels:
    color: green
spec:
  containers:
    - name: webapp-green-container
      image: kodekloud/webapp-color
      command: ["--color", "green"]
        
        
